### ISSUE TITLE
Max values for Maize genetic coef 

### ISSUE THREAD

**Issue by taynaravaleriano** [daquinterop/Py_DSSATTools#10]
When I set a value above 999, for P5 and G2 genetic coeficients I get an error and in the MZCER048.CUL created the value is like  *****

IB0200       DK7220PRO4     . IB0001 275.0   0.0 ***** 800.0  6.30 38.00

**Comment by daquinterop** [comment]
Maximum possible values for P5 and G2 coefficients are 999.0 and 990.0 respectively. See https://github.com/DSSAT/dssat-csm-os/blob/develop/Data/Genotype/MZCER048.CUL for further detail. Furthermore, the Fortran format for those fields is F5.1, it means that the value for those parameters must fit in 5 characters with one decimal place. You can tell that the former condition can't be met when values are above 999.

**Comment by taynaravaleriano** [comment]
Thank you for your reply. 

I got it about the maximum values. 
However, agronomically these values can be higher than 999, since we have new hybrids. So I would like to know if it is possible to change the code to accept this values.

**Comment by daquinterop** [comment]
Unfortunately making those changes is beyond my reach since it would require to change the DSSAT source code. You're right about it, in this case I'd recommend you to write to DSSAT team, they can tell you if it's possible to make those changes for a future release. However, if you are confident enough with FORTRAN, you can try to make those changes yourself. Then you can recompile the model and use that exe instead of the one provided by the DSSATTools.

**Comment by taynaravaleriano** [comment]
Yes, I manually modified the cultivar value in DSSAT and it worked. 
Could you, please, check if it is possible to manage this in fortran?
